### ISSUE TITLE
Bump Android container for gradle 4.6 and Android gradle 3.2.0

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/docker-ci#107]
@tobiasKaminsky do you have the time to take care of this?
Due to the latest dependency bumps the builds now have to download gradle/android-gradle again.

**Comment by tobiasKaminsky** [comment]
I am unsure, if you are allowed to do releases here, but this is mostly it: create a new release here.
Then on building docker it will fetch latest build.gradle and therefore fetch all new deps.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky would I have to do a release or would a tag be enough?

**Comment by tobiasKaminsky** [comment]
Right, Tag is enough, but you only can do a release via webpage and not a single tag, or?

**Comment by AndyScherzinger** [comment]
A release can only be done via the webpage, yes

**Comment by MorrisJobke** [comment]
> @tobiasKaminsky would I have to do a release or would a tag be enough?

A tag is fine. Stick to the naming schema to trigger the auto build on docker hub. ;) (and please just count upwards ;))

**Comment by AndyScherzinger** [comment]
docker image is available and already in use `android-42` :rocket:

**Comment by tobiasKaminsky** [comment]
I know that a tag is enough, but I cannot tag via github.com, therefore I always draft a new release, which then also created a tag…
