### ISSUE TITLE
translationtool: `/.l10nignore` vs. `/l10n/ignorelist`

### ISSUE THREAD

**Issue by korelstar** [nextcloud/docker-ci#118]
What is the state of the art for excluding files from being translated?

If I understand this correctly, `/l10n/ignorelist` was used by the old `l10n.pl` and `/.l10nignore` is used by the new `translationtool.php`. Is this correct?

Why I'm asking: `translationtool.php` has a method `readIgnoreList()` which reads from `/l10n/ignorelist` and returns the content. This method is called from `createPotFile()` in line 64 (https://github.com/nextcloud/docker-ci/blob/master/translations/translationtool/src/translationtool.php#L64). However, the result is not used!

Hence, the content of `/l10n/ignorelist` is totally ignored. If this is intended, we should remove the method `readIgnoreList()`. Otherwise (backward-compatibility?), the result of that method has to be used correctly.

**Comment by MorrisJobke** [comment]
> If I understand this correctly, `/l10n/ignorelist` was used by the old `l10n.pl`

Oh - actually I didn't knew that one 😧 



> and `/.l10nignore` is used by the new `translationtool.php`. Is this correct?

Correct. Just the file `.l10nignore` - one file per line and you are done.

> Hence, the content of `/l10n/ignorelist` is totally ignored. If this is intended, we should remove the method `readIgnoreList()`. Otherwise (backward-compatibility?), the result of that method has to be used correctly.

Wow - actually I totally seemed to miss that. It's good to go. 

> Otherwise (backward-compatibility?), the result of that method has to be used correctly.

Is there actually using some app this? Because we now added those files to the apps we have in our transifex sync setup. If not I would say we should update the apps that still use the old way and go for that.

**Comment by korelstar** [comment]
> Is there actually using some app this? Because we now added those files to the apps we have in our transifex sync setup. If not I would say we should update the apps that still use the old way and go for that.

I don't know. I can't answer this, since I'm too far away from this. I don't even know if the old Perl script is still used somewhere (e.g. in `nextcloud/server`?). However, it looks like the new PHP script is used since 10 months and nobody has complained about it.

Finally, I think someone "official" from Nextcloud has to decide how to deal with this.
