### ISSUE TITLE
How to include specific .txt-file in transifex-bot?

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/docker-ci#199]
Hey @MorrisJobke,

here another request: I want to add some kind of description about how to use markdown for the Notes app (https://github.com/stefan-niedermann/nextcloud-notes/issues/116).

I could store the text in the `strings.xml`-file and it would be translated by transifex. But i do not really want to do that for clarity reasons. Ideal for me was if i could simply place a plain `.md`- or `.txt`-file inside of the android `assets`-folder (similar to https://github.com/nextcloud/docker-ci/issues/198).

- Would this kind of file be respected by the transifex-bot yet?
- If not, can you add support for something like this? Or do you have any other idea about how / where to store such a property?

cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
We could extend generate_metadata.py to also translate this file, but then it is just like everything else in Transifex…

**Comment by stefan-niedermann** [comment]
After some research i think the `raw` folder (which is localized analog to `strings`) is the "android-way" to put localized `.txt`-files in an android app.

> but then it is just like everything else in Transifex…

But this is exactly what i want to achieve - everything in `raw` should go to transifex, get translated there and getting pushed back to my repository.

As far as i understood, the `generate-metadata` script is only processing the already translated files which are yield **from** transifex.

So what i need in the first place, would be that `raw`-values are pushed **to** transifex in the first place.

**Comment by tobiasKaminsky** [comment]
> So what i need in the first place, would be that `raw`-values are pushed **to** transifex in the first place.

This is possible, but as far as I know, it it would be for each file a new resource within nextcloud
(next to android-notes)

So something like
- androidNotes
 - androidNotes-RawFile1
- androidNotes-RawFile2

**Comment by stefan-niedermann** [comment]
Okay, so now the topic is getting serious. I have [a PR with a big text file](https://github.com/stefan-niedermann/nextcloud-notes/pull/857/files#diff-db1b727c667a2f69f0bb16b5f04d07ae) for the Notes app which needs to get translated.

@tobiasKaminsky [your proposal](https://github.com/nextcloud/docker-ci/issues/199#issuecomment-579246691) is fine for me and i don't expect further files to follow. If this is fine for *you*, i would like to ask you for some guidance how to set up this kind of job.

Of course i am always happy to hear alternative solutions. :slightly_smiling_face:

**Comment by stefan-niedermann** [comment]
I solved it by moving all the stuff into my `strings.xml`...
