### ISSUE TITLE
nextcloud-bot invite pending for about a week now

### ISSUE THREAD

**Issue by SergeyMosin** [nextcloud/docker-ci#207]
Appointments app: https://github.com/SergeyMosin/Appointments

![Screenshot_2020-03-06_17-31-04](https://user-images.githubusercontent.com/10747559/76128068-51005000-5fd1-11ea-82b0-e595e5a9df16.png)

**Comment by rullzer** [comment]
Mmmm I have not seen the invite.
Can you resend it?

**Comment by SergeyMosin** [comment]
I just removed and added the nextcould-bot again as the contributor.
Thank you

**Comment by SergeyMosin** [comment]
Hi am I doing something wrong?
I have re-added the nextcloud-bot, and followed directions as per https://docs.nextcloud.com/server/latest/developer_manual/app/view/l10n.html#adding-translations

Any advise would be appreciated, thank you.

**Comment by rullzer** [comment]
Invite accepted. You did it OK. I was just mostly away from my laptop for 2 days due to a sick kid
