### ISSUE TITLE
Add richdocumentscode for translation

### ISSUE THREAD

**Issue by mrkara** [nextcloud/docker-ci#227]
PR for initial i18n/l10n work on the richdocumentscode side: https://github.com/CollaboraOnline/richdocumentscode/pull/29
PR for the CI side: https://github.com/nextcloud/docker-ci/pull/226

Followed instructions here: https://docs.nextcloud.com/server/latest/developer_manual/app/view/l10n.html

By looking at the instructions and the config.json here, it seemed like the app is assumed to be on the root dir of the repo, but we have it under a subdir (nextcloud-app). So we will also add some bits to our build script to copy the l10n directory into the build directory later.

I hope I got everything right for the l10n. Your cooperation/help is much appreciated. Thank you! :)

**Comment by MorrisJobke** [comment]
Looks like it was done in the meantime: #226 

https://github.com/nextcloud/docker-ci/blob/master/translations/config.json#L66
