### ISSUE TITLE
Migration to Vue.js causes trouble with transifex

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/docker-ci#228]
Hello,

the app [cookbook](https://github.com/mrzapp/nextcloud-cookbook) just migrated to Vue.js. Unfortunately, the translation system got broken by it. Almost all translation files were dropped by the bot.

I assume, that the bot did not correctly detect the Vue sources and thus removed non-required entries from the `l10n` files. Of course, we do not want to lose all the translations yet done. So I am coming to you to ask for advice.

If I just take [an example file](https://github.com/mrzapp/nextcloud-cookbook/blob/master/src/components/RecipeEdit.vue) and throw it into a preg matcher against [your detection code](https://github.com/nextcloud/docker-ci/blob/master/translations/translationtool/src/translationtool.php#L330-L332), it seems that the file would be selected for translation.
Unfortunately, I cannot look into the dummy vue file generated. Is there a better way than to hack on the generate pot file and keep the dummy file for inspection?

Thank you very much!

**Comment by skjnldsv** [comment]
cc @juliushaertl @ChristophWurst

**Comment by christianlupus** [comment]
It seems that [some changes in our code[(https://github.com/mrzapp/nextcloud-cookbook/pull/258) brought back the translation files.

We will keep an eye on the commits of the bot for now. If this was the required solution, I'd advice you to put this information into the documentation if possible.

**Comment by ChristophWurst** [comment]
> It seems that [some changes in our code[(https://github.com/[mrzapp/nextcloud-cookbook/pull/258](https://github.com/mrzapp/nextcloud-cookbook/pull/258)) brought back the translation files.

Yes, you need to use `t` with two parameters. That is how the l10n tool is configured.

**Comment by christianlupus** [comment]
Are you willing to keep this issue open for reminder to update the documentation or should I close it?

**Comment by ChristophWurst** [comment]
What update do you need? The JavaScript l10n is documented at https://docs.nextcloud.com/server/19/developer_manual/app/view/l10n.html#javascript

**Comment by christianlupus** [comment]
Yes, I am sorry. I thought with plain JavaScript the single parameter version would be sufficient. My bad, I just saw it was there all the time but a rework to Vue.js dropped it.

Sorry for bothering you.

**Comment by ChristophWurst** [comment]
No worries :)
