### ISSUE TITLE
When translated strings for a language fall below 50%, they are not removed on Android

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/docker-ci#230]
When a translated language falls below the 50% mark, they won't get pushed anymore back from transifex to the upstream repository.

To avoid outdated translations in the upstream repository, there is a delete command to clean up such little translated but no longer pushed languages:
https://github.com/nextcloud/docker-ci/blob/master/translations/handleAppTranslations.sh#L80-L81

It seems though, that this will only affect `json` and `js` files, but translations for Android apps are stored in `xml` files which are not covered by the `rm`.

I am not sure whether or not this issue can simply be solved by adding `xml` to the list of file extensions in this line, therefore just opening an issue instead of a direct PR.

luckily found by coincidence: https://github.com/stefan-niedermann/nextcloud-deck/issues/519
also affected: at least @David-Development and @tobiasKaminsky
for information: @rakekniven

**Comment by tobiasKaminsky** [comment]
All Android related projects use https://github.com/nextcloud/docker-ci/blob/master/translations/handlePlainTranslations.sh

But it is also not there. I will create a PR :+1:

**Comment by stefan-niedermann** [comment]
Ooh, so every app that uses the bot has to be added to [this list](https://github.com/nextcloud/docker-ci/blob/master/translations/handlePlainTranslations.sh#L17)? Maybe some kind of wildcard based solution would be better than? 🤔

**Comment by tobiasKaminsky** [comment]
No, https://github.com/nextcloud/docker-ci/blob/master/translations/handlePlainTranslations.sh#L26 this already applies to your Deck app…
At least "should"…

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/docker-ci/blob/master/translations/Dockerfile-ExternalAndroid-Branched

is being used and thus 75% is minimum.
If you want to change this, please open up a PR.

**Comment by stefan-niedermann** [comment]
I do think so. The trouble is not when new languages are translated far enough to be *added*, the actual issue is that stale languages are not getting *removed* again when they fall below this mark.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/docker-ci/blob/master/translations/handlePlainTranslations.sh#L119

That is still the case, the thing is there is no code to remove languages before the sync which would then also drop the stuff.

For Server apps that works with this lines:
https://github.com/nextcloud/docker-ci/blob/master/translations/handleAppsTranslations.sh#L27-L28

**Comment by tobiasKaminsky** [comment]
We are doing this here:
https://github.com/nextcloud/docker-ci/blob/master/translations/handlePlainTranslations.sh#L16

Due to our change to app sub-directory this failed.
Fix is in: https://github.com/nextcloud/docker-ci/pull/399

**Comment by nickvergessen** [comment]
Now I merged it already, but we check the same folder already with:
https://github.com/nextcloud/docker-ci/blob/master/translations/handlePlainTranslations.sh#L30
