### ISSUE TITLE
Using transifex for Nextloud related app

### ISSUE THREAD

**Issue by Teifun2** [nextcloud/docker-ci#247]
Hello

I was told to ask here for help with transifex.

Im currently developing a smartphone app  https://github.com/Teifun2/nextcloud-cookbook-flutter for a nextcloud "plugin" https://github.com/nextcloud/cookbook. This nextcloud plugin is already integrated with the nextcloud transifex project. As the smartphone app to this plugin will mostly contain the same "texts" that need translation i was wondering if it is possible to use the same transifex project. 

Would it even be possible to use partially the same texts as the cookbook plugin. And what CI and structure would i need to adopt to be accepted into this transifex project? 

I hope i am at the correct place to ask these questions here, and if not then please let me know.

**Comment by MorrisJobke** [comment]
> As the smartphone app to this plugin will mostly contain the same "texts" that need translation i was wondering if it is possible to use the same transifex project.

Theoretically it makes sense, but in reality it's also a lot of work to get the translations of both projects merge them and then put them in transifex. Also this then needs to be kept in sync between the projects (especially spaces and escape sequences could be tricky to match). beside that the transifex tool proposes to just copy the translation for the very same string over from another project.

Long story short: I would just do two projects.

Technically it is documented here: https://docs.nextcloud.com/server/20/developer_manual/basics/front-end/l10n.html#adding-translations But this is more for NC apps.

As this is not a native app, we need to check how to extract the strings from the flutter project and which formats can be exported to. Then the transifex tool needs to be configured - a list of all formats can be found here: https://docs.transifex.com/formats/introduction

I could provide you with the remaining part of integrating this in our transifex flow:

* cloning the repo
* pulling the translations (into *.po files or whatever file format is specified in the transifex config)
* pushing the latest strings
* committing the new translation files
* pushing the code to the repo again

Just tell me where the string files are located and I can send the PR with the transifex config and then I only need to know where the translated string file should be put and the bot will do then it's work of a daily sync between transifex and the repo.

**Comment by Teifun2** [comment]
First of all Thanks a lot for your thorough answer! And excuse me for my late reply!

I looked into it and i probably would use the following library to integrate localization into my app:
https://pub.dev/packages/flutter_translate/example

It seems that this library uses Structured  i18n JSON format, which seems to be a supported format of transifex:
https://docs.transifex.com/formats/json/structured-json

Therefore i know start integrating this translation library. 
One thing i dont understand is the part where you say we need to "export" the strings from the flutter project. Would it suffice if i have one main structured json for en_US as an example? Can Transifex Interpret that? Or do i need to provide the strings that need translation in another format?

Thanks again for your help!

**Comment by MorrisJobke** [comment]
> Would it suffice if i have one main structured json for en_US as an example?

That's how we do it in other repos as well. We generate a file that transifex supports.



> Can Transifex Interpret that?

If it follows their description, then I guess so.



> Or do i need to provide the strings that need translation in another format?

As it is on their docs I would assume that it works.

**Comment by Teifun2** [comment]
Hello im back.

I now added the first translation (en) to my application. Along with the .tx/config file and i invited the nextlcoud-bot to join my repo.

Now as far as i know the only thing left for me to do is to add my repo owner and repo name to the ci configuration file.
I was a little confused because there seem to be different "categories" and i was unsure to which of these i should add my project.

Can you help me with that?
Is there anything else that i need to prepare?

**Comment by MorrisJobke** [comment]
> I now added the first translation (en) to my application. Along with the .tx/config file and i invited the nextlcoud-bot to join my repo.

Sorry - I'm just back here after working through a long list of notifications. Do you mind to send the invitation again.



> Now as far as i know the only thing left for me to do is to add my repo owner and repo name to the ci configuration file.
> I was a little confused because there seem to be different "categories" and i was unsure to which of these i should add my project.
> 
> Can you help me with that?
> Is there anything else that i need to prepare?

Let me add this then.

**Comment by MorrisJobke** [comment]
Should work once the bot has the push right. Resources are at https://www.transifex.com/nextcloud/nextcloud/cookbook_flutter/

**Comment by Teifun2** [comment]
@MorrisJobke Thanks for you help! I did resend the invitation!

**Comment by MorrisJobke** [comment]
> @MorrisJobke Thanks for you help! I did resend the invitation!

Mmmmh .... now the mandatory "CI step "build" needs to pass" fails the push. Should I push to a specific branch instead?

**Comment by Teifun2** [comment]
Is it currently pushing to develop? Develop is what I would prefer but a specific branch is also ok! Is it failing in the forked repo?

**Comment by Teifun2** [comment]
I checked the fork and did not see any changes, how does the build job fail the push? I have never had this issue even if I broke the build job with my push!

**Comment by MorrisJobke** [comment]
> Is it currently pushing to develop? Develop is what I would prefer but a specific branch is also ok! Is it failing in the forked repo?

It pushes currently to master on your repo directly. :)

**Comment by MorrisJobke** [comment]
Should I change to "develop"? Or to any other branch and you merge this from time to time into develop yourself?

**Comment by Teifun2** [comment]
Then lets put it to branch "transifex" and i will merge myself from time to time. I Anyways need to activate new languages in the code as the library only grabs specifically defined languages!

**Comment by MorrisJobke** [comment]
336ecee

**Comment by MorrisJobke** [comment]
And there it is: https://github.com/Teifun2/nextcloud-cookbook-flutter/tree/transifex

**Comment by Teifun2** [comment]
Thanks again for all of your help!
