### ISSUE TITLE
Android translation does not work anymore

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/docker-ci#256]
I re-did the same steps locally and cannot find a mistake.

Do we have any logs?
I would be interested in src/main/res/values/strings.xml

@blizzz maybe?

**Comment by blizzz** [comment]
Something's broken

![Screenshot_20201211_115506](https://user-images.githubusercontent.com/2184312/101895418-cbd14980-3ba7-11eb-9be9-a7344a4d9466.png)

does it help?

**Comment by tobiasKaminsky** [comment]
No, as said above: 


> I would be interested in src/main/res/values/strings.xml

So that I can see what the problem is.

**Comment by tobiasKaminsky** [comment]
There was a linewrap in strings.xml on master branch which confused our system…
