### ISSUE TITLE
Regex issue during transifex string extraction - strings are not extracted

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/docker-ci#259]
Hello. I am currently checking on the issue nextcloud/cookbook#495. I first thought the problem to be in our code. To narrow down the problem, I manually ran the translation tool with `create-pot-files` to check the `*.pot` file generated.

Surprisingly, the `.pot` file contained the relevant part that was criticized in the named issue. One example would be the strings `Fat total` and `Fat content`. Both strings are in our `*.vue` files (discussable if this is a good idea but not this issue's topic) and are correctly reported in the `pot` file in fake vue files
```
#: /tmp/test-vue/cookbook/specialVueFakeDummyForL10nScript.js:73
msgid "Fat content"
msgstr ""

[...]

#: /tmp/test-vue/cookbook/specialVueFakeDummyForL10nScript.js:105
msgid "Fat total"
msgstr ""
```
In transifex web frontend the `Fat content` string is showing up just well. The `Fat total` string is nowhere to find in their page.

After looking into the codes, I assume, the docker container built by [Dockerfile-App](https://github.com/nextcloud/docker-ci/blob/master/translations/Dockerfile-App) will do the synchronization with transifex. Unfortunately, I do not find any hint where this docker file is run and where to look for errors/warnings if there are any.

As we are getting daily updates from the translation bot I assume, the docker image is running in general and taking our repository into consideration. So it seems nothing is broken here in first sight.

Can you please help to elaborate the issue further?

**Comment by MorrisJobke** [comment]
> As we are getting daily updates from the translation bot I assume, the docker image is running in general and taking our repository into consideration. So it seems nothing is broken here in first sight.

Yep it runs without errors. 

> After looking into the codes, I assume, the docker container built by [Dockerfile-App](https://github.com/nextcloud/docker-ci/blob/master/translations/Dockerfile-App) will do the synchronization with transifex.

Correct. It should also work just fine. As we use the exact same tool there. Maybe the Dockerfile-App container still has an outdated translation tool phar. Let me rebuild it and maybe tomorrow everything works.

**Comment by christianlupus** [comment]
I just checked on transifex and the `Fat total` string is not present and ready for translation. We had no changes in the translations tonight.

Can you eventually check the generated `.pot` file and/or the transmitted files to transifex somehow?

**Comment by christianlupus** [comment]
@MorrisJobke Is there anything, I can help with to track down the problem?

**Comment by christianlupus** [comment]
@MorrisJobke I think, I found the culprit of this issue. In our codebase, we have some lines with not only a single translation string but additional (possible non-translated content) as well. Example:
```
<MyComponent :title="t('cookbook', 'This is a text')" class='important'>
```

The problem is the [greedy regular expressions in the translation tool](https://github.com/nextcloud/docker-ci/blob/805773f426cf2e82bca046edfcfa9530be5b60fd/translations/translationtool/src/translationtool.php#L330-L332). In the example above, the single quote `'` is used for the second argument. Due to the greedy modifier, the string `')" class='important` will be used as part of the string to be translated. This is not obvious.

I played a bit with regex variants to get something that might be better used instead of the current regex. This is what I would suggest: [Interactive regex example](https://regex101.com/r/pd2sIV/4)`/\Wt\s*\(\s*(['"])([\w]+)\1\s*,\s*(['"])(([^\\]|\\\3)+?)\3/g`

This regex could be extended for the `n(...)` function as well. I just wanted to ask for your thoughts before I open a PR against the repo. Do you think this could break anything? Please give me your thoughts.

**Comment by christianlupus** [comment]
@MorrisJobke May I ask for your thoughts on it? Should I look for the `n(...)` part as well and open a PR? Or do you consider it obsolete or see other issues with the solution? Otherwise, I'd suggest closing the issue if it is not intended (anymore).

**Comment by nickvergessen** [comment]
> May I ask for your thoughts on it? Should I look for the n(...) part as well and open a PR? Or do you consider it obsolete or see other issues with the solution? Otherwise, I'd suggest closing the issue if it is not intended (anymore).

I'm fine either way. However I'd slightly prefer to not change it, so existing apps are less likely to break
