### ISSUE TITLE
Translations of long strings vs code styling

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/docker-ci#265]
Hello,

I have a longer text that needs to be localized. It is a description of an error case and how the user has to solve it.

When thinking of code styling, such a text will likely need to be broken into multiple lines to fit into the code styling requirements. However in the [parser of the translationtool](https://github.com/nextcloud/docker-ci/blob/805773f426cf2e82bca046edfcfa9530be5b60fd/translations/translationtool/src/translationtool.php#L330-L332) (here using the vue parser as an example), the regex seems to parse the combined file only line by line. So most probably it will only catch only the first part of the string for translation.

Do I miss something here? Or is the best way to simply disable the code style checker for the names line and keep everything on one line?

**Comment by rakekniven** [comment]
Big strings like info.xml are a real pain using Transifex for translation. Please separate them if possible. Jm2c from translators view.

**Comment by christianlupus** [comment]
@rakekniven you mean to separate e.g. the sentences? Because it is discouraged to split up sentences as the grammar might break if I am not completely mistaken.

**Comment by rakekniven** [comment]
If there are more than 300 words there is a issue with the web interface of Transifex.
Your comments are valid AFAIK. But as long as the sentences are complete it will work to separate long text :-)
