### ISSUE TITLE
translationtool does not catch L10n text from .vue files

### ISSUE THREAD

**Issue by tpokorra** [nextcloud/docker-ci#294]
for example in https://github.com/rullzer/twofactor_email/blob/55d07312d30fdd828ba8c443b21cef0abb982ec7/src/components/GatewaySettings.vue#L12

```
<L10n text="You are not using Email as a two-factor authentication method at the moment." />
```
It does not seem the regex in https://github.com/nextcloud/docker-ci/blob/master/translations/translationtool/src/translationtool.php#L319 catches those texts

**Comment by rakekniven** [comment]
Nice catch.
Did you a grep and know how many occurences there are?

**Comment by tpokorra** [comment]
https://github.com/rullzer/twofactor_email/search?q=%22L10n+text%3D%22

and a grep:

```
[timotheus@laptoptphp820G3 twofactor_email]$ find . -name \* -type f -exec grep "L10n text=" {} \; -print
			<L10n text="The Email two-factor authentication method is not available. Do you have an email address set?" />
				<L10n text="You are not using Email as a two-factor authentication method at the moment." />
					<L10n text="Enable" />
					<L10n text="Could not verify your code. Please try again." />
				<L10n text="A confirmation code has been sent to {emailAddress}. Please insert the code here:"
					<L10n text="Verify" />
					<L10n text="Cancel" />
				<L10n text="Your account was successfully configured to receive authentication codes via Email to {emailAddress}."
					<L10n text="Disable" />
./src/components/GatewaySettings.vue
			<L10n text="The server can send authentication codes to your email address." />
./src/components/EmailInstructions.vue
```

**Comment by rakekniven** [comment]
Not sure if your PR is necessary. Many, many NC apps are using Vue and IMHO the code has to be adapted.
t('resource', 'stringtotranslate')

@rullzer Am I right here?

**Comment by rakekniven** [comment]
@tpokorra I will adapt the code to use NC default l10n code. Ok?

**Comment by tpokorra** [comment]
@rakekniven That would be great! Thank you!

**Comment by nursoda** [comment]
What's the status here @rakekniven? Will the tool now catch the OP's example?

**Comment by rakekniven** [comment]
@tpokorra As written above the app should use other translation mechanism and therefor your PR is not necessary. 
We will close here.
