### ISSUE TITLE
Nextcloud Bot pending invite

### ISSUE THREAD

**Issue by JonathanTreffler** [nextcloud/docker-ci#299]
I added the translation configuration for my project fractava/biblio to this repository in #297.
I have also sent a collaborator invite to the Nextcloud Bot on Github, but so far the invite is not accepted and no commits by the bot have been pushed.

![bot invite](https://user-images.githubusercontent.com/28999431/123540190-17130a00-d73e-11eb-9ef8-818d24919410.png)

Is there anything else I need to do or do I just have to wait?

**Comment by skjnldsv** [comment]
You need to wait 
cc @blizzz

**Comment by blizzz** [comment]
accepted
