### ISSUE TITLE
Make the android image smaller

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/docker-ci#31]
A lot of disk space issues are there because most of the space is occupied by the ~9GB android image.

We should try to make this smaller to fit everything on Ramdisks - otherwise I need to disable Ramdisk completely.

cc @AndyScherzinger

**Comment by MorrisJobke** [comment]
cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Is there a way that I can access/check the content of the image?

**Comment by tobiasKaminsky** [comment]
If you want, just ping me on IRC.

**Comment by MorrisJobke** [comment]
> Is there a way that I can access/check the content of the image?

Run it and check it out xD

docker run -ti nextcloudci/android:android-7
