### ISSUE TITLE
Deploy improvement for translation of vue files

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/docker-ci#331]
@nickvergessen Has this improvement been deployed internally at NC? 
Some new changes in vue files at GitHub does not show expected developer notes.

_Originally posted by @rakekniven in https://github.com/nextcloud/docker-ci/issues/321#issuecomment-977170382_

**Comment by nickvergessen** [comment]
> we are currently unable to build a new phar file because there is a bug with upstream. We are in contact with them to resolve it and will proceed as soon as we can build again.

**Comment by nickvergessen** [comment]
Yeah sorry, looks like it. But I have no clue where this goes wrong

**Comment by rakekniven** [comment]
As I do not have any insights of the NC infrastructure I cannot help here 😞

**Comment by rakekniven** [comment]
It is working now. Just checked strings of daily run and it is fine now 😆

**Comment by nickvergessen** [comment]
🙄
