### ISSUE TITLE
Add project "checksum" to Transifex sync

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/docker-ci#333]
- [x] App repo: Add .tx folder including config -> @westberliner
- [x] App repo: Add ignore file -> @westberliner
- [x] App repo: Add l10n folder -> @westberliner
- [x] App repo: Invite "nextcloud bot" with write permissions  -> @westberliner
- [x] docker-ci: add repo info to config.json -> rakekniven   #332 
- [x] Sysadmins of NC: Deploy internally to tx sync process -> @blizzz 
- [x] Transifex: New resource should appear -> rakekniven
- [x] Transifex: Do translations and check sync to repo -> rakekniven

**Comment by rakekniven** [comment]
@blizzz Can you please accept the bot's invitation and deploy?
Thanks.

**Comment by rakekniven** [comment]
Hello @blizzz , please do the normal steps if you can spend some minutes. Gracias.

**Comment by blizzz** [comment]
It does not seem we received an invitation for the nextcloud bot to westberliner/checksum.

**Comment by westberliner** [comment]
Hi @blizzz, I readded the invitation. Could you check again?

**Comment by blizzz** [comment]
> Hi @blizzz, I readded the invitation. Could you check again?

There seems to be a permission issue left. The bot must be able to push directly, right now it is being blocked by a review requirement.

**Comment by westberliner** [comment]
The main branch was protected. Should be fixed now.

**Comment by blizzz** [comment]
> The main branch was protected. Should be fixed now.

Allowing the bot to push there should be sufficient (make it admin). In any case, first translation arrived now!
