### ISSUE TITLE
Drop obsolete versions of PHP

### ISSUE THREAD

**Issue by come-nc** [nextcloud/docker-ci#336]
This repository is getting crowded.

Can I open a PR to drop all images specific to PHP versions below 7.3 that have an equivalent for a newer version?

Maybe keep 7.2 as well, if needed to test things on older Nextcloud versions (7.2 support was dropped in Nextcloud 21, 7.1 in 18 according to documentation).

**Comment by nickvergessen** [comment]
From my POV we could keep them all.

**Comment by skjnldsv** [comment]
I would be ok to drop them, maybe still create dedicated branches for those old versions though. Just so it's easier to find them back if needed?
But this repo is really messy, a little cleanup would not hurt :broom:
