### ISSUE TITLE
Sync for czech language is not working

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/docker-ci#341]
Today https://help.nextcloud.com/t/missing-strings-in-czech-translation/130459/7 came up.

I checked Transifex for mentioned strings and everything is in place.

A look at https://github.com/nextcloud/server/tree/master/apps/files_sharing/l10n shows that czech language hasn't been updated for 5 years.

Did I miss something?

@blizzz Can you check or forward to someone?

Reporting user is using NC v22.2.3 and therefore it looks like an up-to-date issue.

btw. I checked https://demo1.nextcloud.com/status.php to prove issue and it is at v21.0.4. This is outdated for new users. Where to report it?

**Comment by blizzz** [comment]
It's not the only language that was not updated for x years.

@nickvergessen do you have a clue?

**Comment by rakekniven** [comment]
> If less than 50% are translated it is not synced anymore

Are you sure it works this way?
I was thinking that languages which are completed below 50% are not released.
The sync should always take place IMHO.

**Comment by nickvergessen** [comment]
But it's in all repos:
https://github.com/nextcloud/spreed/blob/master/.tx/config#L3

**Comment by nickvergessen** [comment]
The selection in the UI is `cs` as well.
So they just always translated the wrong group on transifex and eventually removed it?

**Comment by rakekniven** [comment]
On Transifex there is only one czech language.

That is way I am asking to delete the cs_CZ files from GitHub.

**Comment by rakekniven** [comment]
See issue https://github.com/nextcloud/server/issues/30501 I filed minutes ago.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/docker-ci/blob/master/translations/handleTranslations.sh#L56-L57

Here is the part where we only download translations which are 50+ percent translated.
Only lib is fetched with 0% and settings with 20%

**Comment by nickvergessen** [comment]
> At Transifex we use "cs_CZ" and the files in Nextcloud use "cs".

Yes, and that is exactly what the lang map should do 🤔

**Comment by nickvergessen** [comment]
Also the mapping still works in Talk:
https://github.com/nextcloud/spreed/blob/master/l10n/cs.js

**Comment by rakekniven** [comment]
OK, back to original issue.
User says this string does not show up correctly localized:
https://www.transifex.com/nextcloud/nextcloud/translate/#cs_CZ/files_sharing/157797997

This string has been translated at Transifex years ago and it is part of the cs file:
https://github.com/nextcloud/server/blob/773c4079653e3ce804d19de0261037405c7756e6/apps/files_sharing/l10n/cs.json#L127

Just checked my local NC v23 instance and it is there.

**Comment by nickvergessen** [comment]
Okay, so cs_CZ should not exist in our files anymore and might really cause the problem. If (for whatever reason) a user has cs_CZ set as language (force language, default language, browser language) and cs_CZ exists, the file will be used instead of us falling back to the cs files which are newer:
https://github.com/nextcloud/server/blob/773c4079653e3ce804d19de0261037405c7756e6/lib/private/L10N/Factory.php#L480-L485
https://github.com/nextcloud/server/blob/773c4079653e3ce804d19de0261037405c7756e6/lib/private/L10N/Factory.php#L318-L326
etc.

So yeah I guess we try to delete the cs_CZ files and see if it fixes it

**Comment by rakekniven** [comment]
I will ask the user to manually delete the files on his installation and report back.

**Comment by rakekniven** [comment]
Post from user:

> So deleting those two files helped. All Strings are now shown translated.

@nickvergessen So should I do one manual cleanup or will you adapt the bot?

**Comment by nickvergessen** [comment]
I think we have to remove them manually. The language does not exist, so zhe sync can not remove it 🙈

**Comment by mikulik86** [comment]
There seems to be a similar issue also with Slovak language. Just FYI.

Anyway, thanks to you guys for such a quick taking care of that.

**Comment by rakekniven** [comment]
Ok, thanks for the information.
