### ISSUE TITLE
Add project "integration_openproject" to Transifex sync

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/docker-ci#348]
- [x] App repo: Add .tx folder including config -> @eneiluj
- [x] App repo: Add ignore file -> @eneiluj
- [x] App repo: Add l10n folder -> @eneiluj
- [x] App repo: Invite "nextcloud bot" with write permissions  -> @eneiluj
- [x] docker-ci: add repo info to config.json -> @eneiluj   #347 
- [x] Sysadmins of NC: Deploy internally to tx sync process -> @blizzz 
- [x] Transifex: New resource should appear -> rakekniven
- [x] Transifex: Do translations and check sync to repo -> rakekniven
- [x] Add resource to [help forum page](https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312)

**Comment by eneiluj** [comment]
@rakekniven Thanks.

"nextcloud bot" has been invited before creating #347. Did you leave this task unchecked because you didn't know or because something is wrong about that?

**Comment by rakekniven** [comment]
Nothing is wrong. I was not aware of it and my permissions are not sufficient to check it myself.
Good work.

**Comment by eneiluj** [comment]
There was a successful translation commit from the bot: https://github.com/nextcloud/integration_openproject/commit/cc64b2d2f8736269cf102b6b3e7930d78bd57af7

We can close this if you want.
