### ISSUE TITLE
l10n: Add mjs to list of javascript filename extensions

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/docker-ci#354]
App gestion started to use javascript files with extension "mjs".

mjs is a extension for module files.

Docs:
* https://v8.dev/features/modules#mjs
* https://v8.dev/features/modules#mjs

See https://github.com/baimard/gestion/issues/146 as issue reference.

**Comment by rakekniven** [comment]
@nickvergessen Is it enought to add "mjs" to https://github.com/nextcloud/docker-ci/blob/a5ee7044742660086f5c1e8019cd7a183f5649b1/translations/translationtool/src/translationtool.php#L70 ?

**Comment by nickvergessen** [comment]
I guess so?
