### ISSUE TITLE
Add file extension "mjs" to list of translatable files

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/docker-ci#358]
The PR has been merged. But the strings from MJS files are still missing.
As there is no issue for this I am kindly asking for help to solve this.

_Originally posted by @rakekniven in https://github.com/nextcloud/docker-ci/issues/355#issuecomment-1054105864_

**Comment by baimard** [comment]
Any news :) ?

**Comment by nickvergessen** [comment]
A recompiling of the translationtool.phar was missing.
This was done, a new docker image created, a manual sync triggered and it worked as per https://github.com/baimard/gestion/issues/146#issuecomment-1063865293

**Comment by baimard** [comment]
Very nice team work !

Merci beaucoup beaucoup !
