### ISSUE TITLE
Nextcloud translation to Persian (Farsi)

### ISSUE THREAD

**Issue by okaeiz** [nextcloud/docker-ci#360]
Hi there!
We have deployed Nextcloud recently and need to localize the interface - which is already done; but incompletely - and want to know how we can include our translations.

**Comment by nickvergessen** [comment]
You need to join the translators team on Transifex:
https://www.transifex.com/nextcloud/teams/64236/fa/

**Comment by rakekniven** [comment]
Add https://help.nextcloud.com/t/no-response-from-the-translators-team-reviewers/135570 for reference
