### ISSUE TITLE
Add project "Transfer" to Transifex sync

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/docker-ci#376]
- [x] App repo: Add .tx folder including config -> @danth
- [x] App repo: Add ignore file -> @danth
- [x] App repo: Add l10n folder -> @danth
- [x] App repo: Invite "nextcloud bot" with write permissions  -> @danth
- [x] docker-ci: add repo info to config.json -> danth   #370 
- [x] Sysadmins of NC: Deploy internally to tx sync process -> @blizzz 
- [x] Transifex: New resource should appear -> rakekniven
- [x] Transifex: Do translations and check sync to repo -> rakekniven

**Comment by rakekniven** [comment]
Related to https://github.com/danth/transfer/issues/9

**Comment by danth** [comment]
> Invite "nextcloud bot" with write permissions

This has now been done.

**Comment by rakekniven** [comment]
Ok, I will see if I can reach the needed person at Nextcloud next week.

**Comment by blizzz** [comment]
- invitation was accepted
- tx syncing id deployed, but:

![Screenshot_20220518_130333](https://user-images.githubusercontent.com/2184312/169024557-fdd7cbdf-ea08-4ae0-b73e-8ac1adee6dc3.png)

yet another reserved word at transifex?

**Comment by rakekniven** [comment]
> yet another reserved word at transifex?

Good point. I will check.

**Comment by rakekniven** [comment]
Renamed resource to "transfer" at Transifex. Slug name is still "nextcloud-transfer" due to reserved words for slugs.

**Comment by rakekniven** [comment]
> Is this caused by the app ID, if so is there anything we can do to avoid it, or will the app ID have to be changed?

Transifex has some reserved words to use for a slug (resource) on their system. Unfortunately this words are not documented and this is a pain, like here. No fault on your side. We now know on how to get around.

**Comment by danth** [comment]
There has been a [successful sync](https://github.com/danth/transfer/commit/fcb62dc01eca2dd03c52978067d765536a49aff3) of the translations from Transifex! Some strings are missing, however there is a [separate issue for that](https://github.com/danth/transfer/issues/25).
