### ISSUE TITLE
Add project "diary" to Transifex sync

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/docker-ci#377]
- [x] App repo: Add .tx folder including config -> @danielroehrig
- [x] App repo: Add ignore file -> @danielroehrig
- [x] App repo: Add l10n folder -> @danielroehrig
- [x] App repo: Invite "nextcloud bot" with write permissions  -> @danielroehrig
- [x] docker-ci: add repo info to config.json -> @danielroehrig   #373 
- [x] Sysadmins of NC: Deploy internally to tx sync process -> @blizzz 
- [x] Transifex: New resource should appear -> rakekniven
- [x] Transifex: Do translations and check sync to repo -> rakekniven

**Comment by danielroehrig** [comment]
Hi @rakekniven I invited nextcloud bot to become a collaborator, but it didn't accept yet. Also, I don't know which config.json you mean. Can you point me in the right direction?

**Comment by rakekniven** [comment]
> I don't know which config.json you mean.

Your PR already addressed the correct file. Link to file: https://github.com/nextcloud/docker-ci/blob/master/translations/config.json 



> I invited nextcloud bot to become a collaborator, but it didn't accept yet.

Sometimes we need to be patient 🍿

**Comment by blizzz** [comment]
I do not see a current invite

**Comment by danielroehrig** [comment]
![image](https://user-images.githubusercontent.com/12596513/169048662-4da191b5-f46b-44e5-98af-a10d7d6093dd.png)
I will try again

**Comment by blizzz** [comment]
@danielroehrig aye, and accepted!

**Comment by rakekniven** [comment]
Still no files have been pushed to diary GH repo 🤔

**Comment by rakekniven** [comment]
Works now. Closing here.
