### ISSUE TITLE
Add project "files_scripts" to Transifex sync

### ISSUE THREAD

**Issue by Raudius** [nextcloud/docker-ci#382]
- [x] App repo: Add .tx folder including config -> @raudius
- [x] App repo: Add ignore file -> @raudius
- [x] App repo: Add l10n folder -> @raudius
- [x] App repo: Invite "nextcloud bot" with write permissions  -> @raudius 
  - [x] Invite pending
- [x] docker-ci: add repo info to config.json -> https://github.com/nextcloud/docker-ci/pull/381
- [x] Sysadmins of NC: Deploy internally to tx sync process -> 
- [x] Transifex: New resource should appear -> 
- [x] Transifex: Do translations and check sync to repo ->

**Comment by rakekniven** [comment]
@blizzz Can you apply invitation?

**Comment by blizzz** [comment]
> @blizzz Can you apply invitation?

done

**Comment by rakekniven** [comment]
It works!
