### ISSUE TITLE
Add project "recognize" to Transifex sync

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/docker-ci#394]
- [x] App repo: Add .tx folder including config -> @marcelklehr
- [x] App repo: Add ignore file -> @marcelklehr
- [x] App repo: Add l10n folder -> @marcelklehr
- [x] App repo: Invite "nextcloud bot" with write permissions  -> @marcelklehr 
  - [ ] Invite pending
- [x] docker-ci: add repo info to config.json -> https://github.com/nextcloud/docker-ci/pull/388
- [x] Sysadmins of NC: Deploy internally to tx sync process -> 
- [x] Transifex: New resource should appear -> @rakekniven 
- [x] Transifex: Do translations and check sync to repo -> @rakekniven 
- [x] Add resource to [wiki](https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312/) -> @rakekniven 

Repo URL: https://github.com/nextcloud/recognize

**Comment by blizzz** [comment]
it's hooked up!

**Comment by marcelklehr** [comment]
Thanks!

**Comment by nickvergessen** [comment]
Config file was broken, fixed with https://github.com/nextcloud/recognize/pull/265/files
