### ISSUE TITLE
Add project "salattime" to Transifex sync

### ISSUE THREAD

**Issue by medismail** [nextcloud/docker-ci#397]
- [x] App repo: Add .tx folder including config -> @medismail
- [x] App repo: Add ignore file -> @medismail
- [x] App repo: Add l10n folder -> @medismail
- [x] App repo: Invite "nextcloud bot" with write permissions  -> @medismail 
  - [x] Invite pending
- [x] docker-ci: add repo info to config.json -> https://github.com/nextcloud/docker-ci/pull/398
- [x] Sysadmins of NC: Deploy internally to tx sync process -> 
- [x] Transifex: New resource should appear -> @rakekniven 
- [ ] Transifex: Do translations and check sync to repo -> @rakekniven 
- [x] Add resource to [wiki](https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312/) -> @rakekniven 

Repo URL: https://github.com/medismail/salattime

**Comment by medismail** [comment]
Thank you for reply, the ignore file is added.

**Comment by medismail** [comment]
thanks again great weekend :)

**Comment by nickvergessen** [comment]
If I remember correctly invites expire after 7 days. The respective people are now back, so if you could invite the nextcloud bot once again, that would be very helpful.

**Comment by mgallien** [comment]
Invitation has been accepted
you can proceed

**Comment by medismail** [comment]
> If I remember correctly invites expire after 7 days. The respective people are now back, so if you could invite the nextcloud bot once again, that would be very helpful.

A new invitation is sent.

**Comment by medismail** [comment]
> > A new invitation is sent.
> 
> No need, see comment of mgallien.

Ok I will cancel.

**Comment by nickvergessen** [comment]
Yeah I assume due to the canceled invite from above.

@medismail can you check if the bot still has access and if not invite it. I assume your canceled invite removed the previous accepted state and removed all permissions.

**Comment by nickvergessen** [comment]
Reinvite was accepted and it works now.
