### ISSUE TITLE
 Add project "files_libreoffice_edit" to Transifex sync 

### ISSUE THREAD

**Issue by smehrbrodt** [nextcloud/docker-ci#400]
- [x] Transifex: New resource should appear -> @rakekniven 
- [ ] Transifex: Do translations and check sync to repo -> @rakekniven 
- [x] Add resource to [wiki](https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312/) -> @rakekniven 

Repo URL: https://github.com/allotropia/nextcloud_files_libreoffice_edit

**Comment by nickvergessen** [comment]
Can you go to https://github.com/allotropia/nextcloud_files_libreoffice_edit/settings/access
And add `nextcloud-bot` with admin permissions please, so it can push the translations?

Also https://github.com/allotropia/nextcloud_files_libreoffice_edit/pull/18 is necessary

**Comment by smehrbrodt** [comment]
Write access should be enough according to https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#setup-of-the-transifex-sync

I already added the nextcloud-bot with write access before:

![grafik](https://user-images.githubusercontent.com/3502738/185939566-632a84d6-cf24-4e1b-9127-00aade3d7f96.png)

**Comment by nickvergessen** [comment]
> I already added the nextcloud-bot with write access before:

Okay let's see, as long as no branch protection is set up that should be good enough IIRC.

**Comment by mgallien** [comment]
Invitation of `nextcloud-bot` has been accepted.
you can proceed

**Comment by nickvergessen** [comment]
Sync worked: https://github.com/allotropia/nextcloud_files_libreoffice_edit/commit/7895d87ba77d6ee2db128d861ae84a50bbbb5b09

(For now it wiped the files because the values are not stored in Transifex yet).

**Comment by nickvergessen** [comment]
In the other issue you added:

> Transifex: New resource should appear
> Transifex: Do translations and check sync to repo
> Add resource to [wiki](https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312/)

**Comment by nickvergessen** [comment]
Taking over for now:

- [ ] translations-app/handleAppTranslations.sh needs to read the resource name from the `.tx/config` file and rename the pot file to such before running `tx push`
