### ISSUE TITLE
Fix lang resource not appearing on Transifex please

### ISSUE THREAD

**Issue by p-bo** [nextcloud/docker-ci#409]
According existence of transifex config file in this project it seems, that there was attempt for adding this following instructions:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations
But it seems, that this wasn't completed yet:
![obrazek](https://user-images.githubusercontent.com/12208593/187410657-8b9bb935-efaf-4bfd-ad96-6aaf5062b809.png)

Would it be possible to find (or cooperate with Nextcloud CI admins - as for example in this case https://github.com/nextcloud/docker-ci/issues/400 ) please?

Thanks :-)

**Comment by nickvergessen** [comment]
Transfering this one to the docker-ci repo as the socialsharing apps are handled special because multiple sources are in one repo.

Ref is https://github.com/nextcloud/docker-ci/blob/master/translations/handleAppsTranslations.sh

Will have a look after my vacation

**Comment by p-bo** [comment]
@nickvergessen
Thanks for picking this, because:

- much more translators will get involved, because without it, they will newer even know about possibility to translate this app - example of benefits for project known in this manner for community of Nextcloud translators
- also, as app is evolving, when some string(s) in app is/are changed/added, in case of continuous translation workflow translators are noticed intermediately and strings are translated before new version is released. In contrast with situation, that this change (in source strings) is only silently published in git repo and no one will (get) notice(d) till never version with untranslated strings get released (proactive vs retroactive).
- when one (of translators) will during using this app notice possibility to translate something in better manner, it is much efficient (especially for minor changes) to do this in translation tool than edit file directly in git. For example in case of one letter changes (misspelled words, etc.) has change directly in git such overhead (many steps to change just one letter), that these type of tweaks are rare due this (loss of quality for users)

To conclude: with continuous translation workflow, result is, that users of an app are getting more complete and more polished localization, so their user experience is much more pleasant.

**Comment by nickvergessen** [comment]
Works now https://github.com/nextcloud/socialsharing/commit/df8699c7c3d419fd3f37413ebee8c5c9742729d2

**Comment by p-bo** [comment]
Great! Many thanks, translated already into my language and others will arrive quickly for sure too :-)
