### ISSUE TITLE
Add "mediadc" to Transifex sync

### ISSUE THREAD

**Issue by andrey18106** [nextcloud/docker-ci#449]
# 👤 App repository

**To be done by you**

- [x] Link to your repository: https://github.com/andrey18106/mediadc
- [x] If the app is personal repository
    - [x] Invite `nextcloud-bot` with write permissions
    - [x] Make sure all translated branches do **not** have branch protection enabled, see https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#setup-of-the-transifex-sync for more details
- [x] Create file `l10n/.gitkeep` with empty content
- [x] Add `.l10nignore` to exclude compiled JS files and thirdparty code, e.g. ignoring compiled javascript assets and composer PHP dependencies in the vendor/ directory:
```
js/
vendor/
```
- [x] Create file `.tx/config` with the following content, replace `{{APPID}}` with your app id 3 times:
```ini
[main]
host     = https://www.transifex.com
lang_map = hu_HU: hu, nb_NO: nb, sk_SK: sk, th_TH: th, ja_JP: ja, bg_BG: bg, cs_CZ: cs, fi_FI: fi

[o:nextcloud:p:nextcloud:r:{{APPID}}]
file_filter = translationfiles/<lang>/{{APPID}}.po
source_file = translationfiles/templates/{{APPID}}.pot
source_lang = en
type        = PO
```

# 🏗️ Sysadmin team
- [x] 👀 Ensure access:
    - [ ] Nextcloud-Org repository: Add `nextcloud-bot` with admin permissions
    - [x] Other repositories:
        - [x] Ensure the invite was accepted
        - [x] Ensure the app certificate is linked to the same repository/author https://github.com/nextcloud/app-certificate-requests
- [x] ⚙️ Ensure repository setup:
    - [x] `.tx/config`
    - [x] `l10n/.gitkeep`
    - [x] `.l10ignore`
- [x] ➕ Add `"Owner Repository",` into https://github.com/nextcloud/docker-ci/edit/master/translations/config.json
    - [x] Pull request: https://github.com/nextcloud/docker-ci/pull/452
- [x] 🏃Run action: https://github.com/nextcloud/docker-ci/actions/workflows/docker.yml
   1. Path: `translations-app`
   2. File: `Dockerfile`
   3. Suffix empty ``
   4. Tag `latest`
- [x] 🔑 SSH into translation machine: `ssh root@transifex-sync.nextcloud.com`
- [x] ↩️ Change dir: `cd /srv/docker-ci`
- [x] ⬇️ Pull: `git pull origin master`
- [x] 🧑‍💻 Run the first sync manually:

```sh
docker run -v /srv/cronie-data/transifexrc:/root/.transifexrc \
    -v /srv/cronie-data/gpg:/gpg \
    -v /srv/cronie-data/ssh/id_rsa:/root/.ssh/id_rsa \
    --rm -i ghcr.io/nextcloud/continuous-integration-translations-app \
    AUTHOR APPID
```

# 🔣 Translation team
- [ ] Transifex: New resource should appear
- [ ] Transifex: Do translations and check sync to repo
- [ ] Add resource to [wiki](https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312/)

**Comment by nickvergessen** [comment]
```
To github.com:andrey18106/mediadc
 ! [remote rejected] main -> main (protected branch hook declined)
```

@andrey18106 you have to remove the branch protection

**Comment by andrey18106** [comment]
> ```
> To github.com:andrey18106/mediadc
>  ! [remote rejected] main -> main (protected branch hook declined)
> ```
> 
> @andrey18106 you have to remove the branch protection

Removed branch protection.

**Comment by nickvergessen** [comment]
Sync worked now: https://github.com/andrey18106/mediadc/commit/a3fb56e5beedba5e3947ec1757f7c0b10cedd041

**Comment by andrey18106** [comment]
@nickvergessen Hi! There is no issue template for question in this repository, so I'll ask you here, as it is related to mediadc.

How can I move [mediadc](https://github.com/andrey18106/mediadc) repository properly to [cloud-py-api](https://github.com/cloud-py-api). In particular, how to update all the links in the Nextcloud Appstore, and here at Transifex sync.

**Comment by andrey18106** [comment]
@nickvergessen Thanks for response. We have transferred mediadc, and now it needs to be updated in Transifex sync.

Now repo located here: https://github.com/cloud-py-api/mediadc.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/docker-ci/pull/499
