### ISSUE TITLE
Bot does not extract translations from vue files if first arg is not string

### ISSUE THREAD

**Issue by zorn-v** [nextcloud/docker-ci#457]
If you have first arg (app name) of `t`/`n` function as var (for example imported from some `common.js`) bot does not extract that string to translate.
https://github.com/zorn-v/nextcloud-social-login/blob/ce92a4d447d1246952dd021c6bb66d7507019cc9/src/components/Settings.vue#L8 for example

Checks are here

https://github.com/nextcloud/docker-ci/blob/8109b94ba1735548365aebb7d5dc88e64c15c1c0/translations/translationtool/src/translationtool.php#L330-L332

https://github.com/nextcloud/docker-ci/blob/8109b94ba1735548365aebb7d5dc88e64c15c1c0/translations/translationtool/src/translationtool.php#L342-L344

**Comment by nickvergessen** [comment]
The problem is we can not know the value of the variables to see if it should be added to the extracted resource.

**Comment by zorn-v** [comment]
No, this value is just ignored. Also extract from js works fine with it.
For `t`
```php
$matches0 = array_merge($singleQuoteMatches[0], $doubleQuoteMatches[0], $templateQuoteMatches[0]);
$matches2 = array_merge($singleQuoteMatches[2], $doubleQuoteMatches[2], $templateQuoteMatches[2]);
```
For `n`
```php
$matches0 = array_merge($singleQuoteMatches[0], $doubleQuoteMatches[0], $templateQuoteMatches[0]);
$matches2 = array_merge($singleQuoteMatches[2], $doubleQuoteMatches[2], $templateQuoteMatches[2]);
$matches3 = array_merge($singleQuoteMatches[3], $doubleQuoteMatches[3], $templateQuoteMatches[3]);
```

As you can see `matches[1]` (app name) does not take into account

**Comment by nickvergessen** [comment]
Sociallogin jumped from 66 to 79 strings on transifex, so seems to have worked
