### ISSUE TITLE
Add integration apps

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/docker-ci#466]
# 👤 App repository

- [x] Link to your repository:
    * https://github.com/julien-nc/integration_dropbox
    * https://github.com/julien-nc/integration_excalidraw
    * https://github.com/julien-nc/integration_mattermost
    * https://github.com/julien-nc/integration_nuiteq
    * https://github.com/julien-nc/integration_onedrive
    * https://github.com/julien-nc/integration_zimbra
    * https://github.com/julien-nc/picker
    * https://github.com/julien-nc/welcome

- [x] If the app is personal repository
    - [x] Invite `nextcloud-bot` with write permissions
    - [x] Make sure all translated branches do **not** have branch protection enabled, see https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#setup-of-the-transifex-sync for more details
- [x] Create file `l10n/.gitkeep` with empty content
- [x] Add `.l10nignore` to exclude compiled JS files and thirdparty code, e.g. ignoring compiled javascript assets and composer PHP dependencies in the vendor/ directory:
```
js/
vendor/
```
- [x] Create file `.tx/config` with the following content, replace `{{APPID}}` with your app id 3 times:
```ini
[main]
host     = https://www.transifex.com
lang_map = hu_HU: hu, nb_NO: nb, sk_SK: sk, th_TH: th, ja_JP: ja, bg_BG: bg, cs_CZ: cs, fi_FI: fi

[o:nextcloud:p:nextcloud:r:{{APPID}}]
file_filter = translationfiles/<lang>/{{APPID}}.po
source_file = translationfiles/templates/{{APPID}}.pot
source_lang = en
type        = PO
```

# 🏗️ Sysadmin team
- [x] 👀 Ensure access:
    - [ ] Nextcloud-Org repository: Add `nextcloud-bot` with admin permissions
    - [x] Other repositories:
        - [x] Ensure the invite was accepted
        - [x] Ensure the app certificate is linked to the same repository/author https://github.com/nextcloud/app-certificate-requests
- [x] ⚙️ Ensure repository setup:
    - [x] `.tx/config`
    - [x] `l10n/.gitkeep`
    - [x] `.l10ignore`
- [x] ➕ Add `"Owner Repository",` into https://github.com/nextcloud/docker-ci/edit/master/translations/config.json
    - [x] Pull request: https://github.com/nextcloud/docker-ci/pull/465
- [x] 🔑 SSH into translation machine: `ssh root@transifex-sync.nextcloud.com`
- [x] ↩️ Change dir: `cd /srv/docker-ci`
- [x] ⬇️ Pull: `git pull origin master`
- [x] 🧑‍💻 Run the first sync manually:

```sh
docker run -v /srv/cronie-data/transifexrc:/root/.transifexrc \
    -v /srv/cronie-data/gpg:/gpg \
    -v /srv/cronie-data/ssh/id_rsa:/root/.ssh/id_rsa \
    --rm -i ghcr.io/nextcloud/continuous-integration-translations-app \
    AUTHOR APPID
```

# 🔣 Translation team
- [x] Transifex: New resource should appear
- [x] Transifex: Do translations and check sync to repo
- [x] Add resource to [wiki](https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312/)

**Comment by julien-nc** [comment]
refs #465

**Comment by nickvergessen** [comment]
Was able to run some of them, but the following 4 are blocked by branch protection:

* julien-nc integration_dropbox
* julien-nc integration_nuiteq
* julien-nc integration_zimbra
* julien-nc picker

**Comment by nickvergessen** [comment]
All worked now
