### ISSUE TITLE
Uploading existing manually created translations to transifex after switching to transifex

### ISSUE THREAD

**Issue by rotdrop** [nextcloud/docker-ci#471]
> For each resource (=app) and each language for it, there is upload file button on Transifex, not sure regarding import data 

Thanks for your hints! I will have look once things are set up for the app.

_Originally posted by @rotdrop in https://github.com/nextcloud/docker-ci/issues/467#issuecomment-1311613567_
      
If one already has translations for ones app (which of course must fit into the used tool-chain: GNU gettext) then it is quite easy to upload existing translations to transifex. However, there are some pitfalls:

1. Before migrating to transifex one must update the existing translation template file `.pot` to the current version of the  source code
   - otherwise for one there will be a merge conflict when transifex tries to push its own `.pot` file
   - I also suppose that consequently afterwards the translation upload (the `.po` file will fail as it does not match the template)
2. Commit and push your own updated template file. It is probably also a good idea to sync the existing translation `.po` files with the updated template and commit and push those as well.
3. Follow the procedure described in the issue template for registering your app. See there.
4. Wait until the initial sync from transifex has been done.
5. Register yourself with transifex and join the Nextcloud community, join the proper language teams etc.
6. Navigate in the transifex web-interface to the Nextcloud project and seach for your app in the `Resources` section
7. Select your app and the language you want to upload
8. There should be an upload button (don't choose `xliff`, just "upload")
9. Recover the translation `.po` file from you git history, download it to you computer and upload it into transifex

At least for me this procedure worked and I now have for my pre-existing translations everything I had before moving to transifex.

... and now and go to my other app where I did not sync the template `.pot` file (see point 1. above) before migrating to transifex and see whether I can rescue my translations ... ;)

**Comment by nickvergessen** [comment]
I uploaded your previous de/*.po files for your apps

**Comment by nickvergessen** [comment]
I also triggered another manual sync for both your apps and that brought back the german strings again:
* https://github.com/rotdrop/nextcloud-app-files-archive/commit/8f6e4a5a67543ff5d52ef84055f68be2eb32265c#diff-945df1d457e21279690c9addf5cf481a4dcc4a9aa7c468559314747989849064
* https://github.com/rotdrop/nextcloud-app-pdf-downloader/commit/fa9639dadeeb4ba1683bb0b1c4bb91487545b59e#diff-7c35eadec8d53ccf9315e025b8f81c2caa571bc228e69a65865dc43b4c49d79f

**Comment by rotdrop** [comment]
> 

Thank you, however, I also uploaded the translations for the pdf_downloader app which appeared not to be present (or I just overlooked that) and acutally now see that the translations for the pdf_downloader app are already there.

So many thanks for taking care of that.

Would that be the usual service from your side? In that case we should just close this issue as superfluous.

**Comment by nickvergessen** [comment]
Well this is a one time thing.

Most apps don't have translations before hand. I only ever saw manual l10n/*js(on) files being there, basically never PO or POT files.
But we could add it to the app maintainer steps

**Comment by rotdrop** [comment]
> I also triggered another manual sync for both your apps and that brought back the german strings again:
> 
>     * [rotdrop/nextcloud-app-files-archive@8f6e4a5#diff-945df1d457e21279690c9addf5cf481a4dcc4a9aa7c468559314747989849064](https://github.com/rotdrop/nextcloud-app-files-archive/commit/8f6e4a5a67543ff5d52ef84055f68be2eb32265c#diff-945df1d457e21279690c9addf5cf481a4dcc4a9aa7c468559314747989849064)

There is an issue, I thing: while everything works for the "pdf_downloader" app it appears that in the "files_archive" app -- that was the one with the merge-conflict and the pull-request for deleting the translationsfiles/ directory -- now there is no translationsfiles/ directory, also not after the second sync.

**Comment by nickvergessen** [comment]
> now there is no translationsfiles/ directory, also not after the second sync.

The directory is not supposed to be there at all. It is a temporary directory inside the sync job.
You can savely delete it and it will continue to work just fine.

**Comment by rotdrop** [comment]
> > now there is no translationsfiles/ directory, also not after the second sync.
> 
> The directory is not supposed to be there at all. It is a temporary directory inside the sync job. You can savely delete it and it will continue to work just fine.

Ok, great. Interestingly, if it is there then Transifex will happily sync its template `.pot` and also the `.po` translation files which is the case for the pdf_downloader app ATM.

So kind thanks for the hints.

**Comment by rotdrop** [comment]
> Well this is a one time thing.
> 
> Most apps don't have translations before hand. I only ever saw manual l10n/*js(on) files being there, basically never PO or POT files. But we could add it to the app maintainer steps

I would vote against adding it. If I am really the only nerd which is doing such things then one should not confuse the others.

I am closing this issue now. Thanks again!
