### ISSUE TITLE
Transifex translation for files_linkeditor

### ISSUE THREAD

**Issue by te-online** [nextcloud/docker-ci#475]
# 👤 App repository

**To be done by you**

- [x] Link to your repository: https://github.com/te-online/files_linkeditor/
- [x] If the app is not in the Nextcloud organisation
    - [x] Invite `nextcloud-bot` with write permissions
    - [x] Make sure all translated branches do **not** have branch protection enabled, see https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#setup-of-the-transifex-sync for more details
- [x] Create file `l10n/.gitkeep` with empty content (dir exists)
- [x] Add `.l10nignore` to exclude compiled JS files and thirdparty code, e.g. ignoring compiled javascript assets and composer PHP dependencies in the vendor/ directory:
```
js/
vendor/
```
- [x] Create file `.tx/config` with the following content, replace `{{APPID}}` with your app id 3 times:
```ini
[main]
host     = https://www.transifex.com
lang_map = hu_HU: hu, nb_NO: nb, sk_SK: sk, th_TH: th, ja_JP: ja, bg_BG: bg, cs_CZ: cs, fi_FI: fi

[o:nextcloud:p:nextcloud:r:{{APPID}}]
file_filter = translationfiles/<lang>/{{APPID}}.po
source_file = translationfiles/templates/{{APPID}}.pot
source_lang = en
type        = PO
```

# 🏗️ Sysadmin team
- [x] 👀 Ensure access:
    - [ ] Nextcloud organisation repository: Add `nextcloud-bot` with admin permissions
    - [x] Other repositories:
        - [x] Ensure the invite was accepted
        - [x] Ensure the app certificate is linked to the same repository/author https://github.com/nextcloud/app-certificate-requests
- [x] ⚙️ Ensure repository setup:
    - [x] `.tx/config`
    - [x] `l10n/.gitkeep`
    - [x] `.l10ignore`
- [x] ➕ Add `"Owner Repository",` into https://github.com/nextcloud/docker-ci/edit/master/translations/config.json
    - [x] Pull request: https://github.com/nextcloud/docker-ci/pull/476
- [x] 🔑 SSH into translation machine: `ssh root@transifex-sync.nextcloud.com`
- [x] ↩️ Change dir: `cd /srv/docker-ci`
- [x] ⬇️ Pull: `git pull origin master`
- [x] 🧑‍💻 Run the first sync manually:

```sh
docker run -v /srv/cronie-data/transifexrc:/root/.transifexrc \
    -v /srv/cronie-data/gpg:/gpg \
    -v /srv/cronie-data/ssh/id_rsa:/root/.ssh/id_rsa \
    --rm -i ghcr.io/nextcloud/continuous-integration-translations-app \
    AUTHOR APPID
```

# 🔣 Translation team
- [x] Transifex: New resource should appear
- [x] Transifex: Do translations and check sync to repo
- [x] Add resource to [wiki](https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312/)

**Comment by nickvergessen** [comment]
Will have a look later this week

**Comment by nickvergessen** [comment]
Just for the record, you seem to have added a translation branch, but not the "stable" branch to the backport file.

So currently the following branches are translated:
* main
* translation

My recommendation would be to change the `.tx/backport` file to the following content:
```
stable
```

then it would get source strings from main and stable and also push them to those branches.

What was the idea behind the translation branch?

**Comment by nickvergessen** [comment]
Apart from that misspecification everything is done and seems to work fine

**Comment by te-online** [comment]
@nickvergessen Thanks for looking into it and being thorough, I appreciate it 👍 

I was trying to find a way around the limitation that I couldn't have a protected main branch. I had a hunch that maybe I could make `stable` my main branch in Github and have transifex translate on `main` and `translation` – whatever works. 

I wouldn't mind keeping these branches in sync in terms of translations as long as I don't have to give up main branch protection ("main" as in Github's reference branch for opening PRs and such).

If that doesn't work, I'll have to live with an unprotected main branch, because I don't want to go for any of the other options either (creating an organization or moving to the nextcloud org) :-/

**Comment by nickvergessen** [comment]
It works as intended then.
Just as a comment. Since it's a private repo only you have write access by default so only you (and now the nextcloud-bot) can merge and push stuff.
So while protection is of course useful in some cases, I'm not sure what you try to protect against?😅
The only difference is that it requires admin privilege instead of write privilege to merge with failing tests (but user list is mostlikely the same, so not changing) and PRs have to be used (which also only affects you and the bot)?
Or am I missing something?

**Comment by te-online** [comment]
> So while protection is of course useful in some cases, I'm not sure what you try to protect against?😅

I might be wrong, because my experience with managing permissions in Github is limited and documentation seems to mostly focus on repositories within organizations.

But for me there are 2 main reasons:

1. I think it's good practice to protect your default branch and Github actually warns you when you don't do that. It reduces the surface for supply-chain attacks. I don't think it's a good idea to give an integration (like transifex) permission to manipulate your default branch from which I create releases and have automated webhooks configured.
2. Additionally, since the repository in question is not part of an organization, I can't manage permissions for members. They are all "collaborators". That means if I want to add a member from the community as a collaborator and my default branch is not protected, they can just merge (if I understand Github's documentation correctly).

**Comment by te-online** [comment]
Hey @nickvergessen I have two follow-up questions, any chance you can help with those? 😅 

1. How do I get the scanner to look for `t('...')` calls in `.svelte` files? If that's not possible, I can un-minify the bundle and have it search in the bundle instead. In that case – will it ignore duplicate translation strings (from source .js files and bundle.js)?
2. How can I import existing translations in the repository into transifex? Right now it removes the existing translations in their respective .js and .json files (also, because it didn't scrape the right strings yet, see 1.)

**Comment by nickvergessen** [comment]
1. I guess it would need a similar workaround liek vue:
https://github.com/nextcloud/docker-ci/blob/master/translations/translationtool/src/translationtool.php#L319-L322
   Duplicates don't matter, or well don't exist really. They will use the same translation string and translators will only see 1 string

2. You can do a one time import, but that won't help if the source string is not detected. So I guess we either have to change the translationtool code to also extract on svelte files or we try extracting from your bundle. But I guess that should work already? Or is it because the keyword is `t` but your code uses `window.t` ?

**Comment by p-bo** [comment]
> 1. How do I get the scanner to look for `t('...')` calls in `.svelte` files?

(just realized, that coincidently I saw it somewhere in past and was able to find it in browser history)
It seems, that .svelte files are not among processed ones - see https://github.com/danth/transfer/issues/25#issuecomment-1132955324
