### ISSUE TITLE
Use conventional commits for translation pushes

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/docker-ci#479]
I am experimenting with conventional commits and automated releases and stumbled over the `[tx-robot] ...` commit messages.

To comply with https://www.conventionalcommits.org/en/v1.0.0/#summary it would be cool if the bot could send commits in the conventional format, e.g. `fix: Update translations from Transifex`.

Automation could classify that commit, generate a changelog and do the release.

**Comment by nickvergessen** [comment]
[Scopes exist](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-scope), so we could use `l10n`

For translations:
```
Fix(l10n): Update translations from Transifex
```
For config and other changes:
```
Fix(l10n): Update transifex configuration
```
