### ISSUE TITLE
Request translations for draw.io app

### ISSUE THREAD

**Issue by m-mohamedin** [nextcloud/docker-ci#494]
# 👤 App repository

**To be done by you**

- [x] Link to your repository: https://github.com/jgraph/drawio-nextcloud
- [x] If the app is not in the Nextcloud organisation
    - [x] Invite `nextcloud-bot` with write permissions
    - [x] Make sure all translated branches do **not** have branch protection enabled, see https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#setup-of-the-transifex-sync for more details
- [x] Create file `l10n/.gitkeep` with empty content
- [x] Add `.l10nignore` to exclude compiled JS files and thirdparty code, e.g. ignoring compiled javascript assets and composer PHP dependencies in the vendor/ directory:
```
js/
vendor/
```
- [x] Create file `.tx/config` with the following content, replace `{{APPID}}` with your app id 3 times:
```ini
[main]
host     = https://www.transifex.com
lang_map = hu_HU: hu, nb_NO: nb, sk_SK: sk, th_TH: th, ja_JP: ja, bg_BG: bg, cs_CZ: cs, fi_FI: fi

[o:nextcloud:p:nextcloud:r:{{APPID}}]
file_filter = translationfiles/<lang>/{{APPID}}.po
source_file = translationfiles/templates/{{APPID}}.pot
source_lang = en
type        = PO
```

# 🏗️ Sysadmin team
- [x] 👀 Ensure access:
    - [ ] Nextcloud organisation repository: Add `nextcloud-bot` with admin permissions
    - [x] Other repositories:
        - [x] Ensure the invite was accepted
        - [x] Ensure the app certificate is linked to the same repository/author https://github.com/nextcloud/app-certificate-requests
- [x] ⚙️ Ensure repository setup:
    - [x] `.tx/config`
    - [x] `l10n/.gitkeep`
    - [x] `.l10ignore`
- [x] ➕ Add `"Owner Repository",` into https://github.com/nextcloud/docker-ci/edit/master/translations/config.json
    - [x] Pull request: https://github.com/nextcloud/docker-ci/pull/496
- [x] 🔑 SSH into translation machine: `ssh root@transifex-sync.nextcloud.com`
- [x] ↩️ Change dir: `cd /srv/docker-ci`
- [x] ⬇️ Pull: `git pull origin master`
- [x] 🧑‍💻 Run the first sync manually:

```sh
docker run -v /srv/cronie-data/transifexrc:/root/.transifexrc \
    -v /srv/cronie-data/gpg:/gpg \
    -v /srv/cronie-data/ssh/id_rsa:/root/.ssh/id_rsa \
    --rm -i ghcr.io/nextcloud/continuous-integration-translations-app \
    AUTHOR APPID
```

# 🔣 Translation team
- [x] Transifex: New resource should appear
- [x] Transifex: Do translations and check sync to repo
- [x] Add resource to [wiki](https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312/)

**Comment by nickvergessen** [comment]
Hi, sorry for the delay. The person managing the GitHub account of the bot is currently out sick. Trying to find if their sick-leave replacement has access otherwise this will take another week

**Comment by nickvergessen** [comment]
The request was accepted but syncing does not work at the moment.
The scripts require a branch named `main` or `master` to be the base of work. `dev` can by synced additionally, but we checkout master/main to check the `.tx/backport` file and so that does not work at the moment.
So if possible I would recommend that you rename your branch `dev` to `main`

**Comment by m-mohamedin** [comment]
Thanks for your reply.
Done: `dev`  branch renamed to `main`

**Comment by nickvergessen** [comment]
Sync worked now:
https://github.com/jgraph/drawio-nextcloud/commit/4324d6e2b403806731fe5386c7de839ffc47863d

**Comment by m-mohamedin** [comment]
@nickvergessen Can you please tell me how to import existing translation. Almost all existing translation are gone when synced.
Thanks

**Comment by nickvergessen** [comment]
In what format do you have them?
Only if there are po or pot files we can import them to transifex.

**Comment by m-mohamedin** [comment]
Unfortunately, the translation is in js and json format. I'll see if I can convert them and get back to you.
Thanks

**Comment by nickvergessen** [comment]
Well I think after the weekend our community people will have translated most things already I guess. So not sure it's worth a lot of effort.

**Comment by nickvergessen** [comment]
Yeah, would be helpful. But as long as no one writes it, it does not exist :(
