### ISSUE TITLE
Add "workflow_ocr" to Transifex sync

### ISSUE THREAD

**Issue by R0Wi** [nextcloud/docker-ci#518]
See also  https://github.com/R0Wi-DEV/workflow_ocr/issues/146

# 👤 App repository

**To be done by you**

- [x] Link to your repository: https://github.com/R0Wi-DEV/workflow_ocr
- [x] If the app is not in the Nextcloud organisation
    - [x] Invite `nextcloud-bot` with ~~write~~ admin permissions
    - [x] ~~Make sure all translated branches do **not** have branch protection enabled, see https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#setup-of-the-transifex-sync for more details~~
- [x] Create file `l10n/.gitkeep` with empty content
- [x] Add `.l10nignore` to exclude compiled JS files and thirdparty code, e.g. ignoring compiled javascript assets and composer PHP dependencies in the vendor/ directory:
```
js/
vendor/
```
- [x] Create file `.tx/config` with the following content, replace `{{APPID}}` with your app id 3 times:
```ini
[main]
host     = https://www.transifex.com
lang_map = hu_HU: hu, nb_NO: nb, sk_SK: sk, th_TH: th, ja_JP: ja, bg_BG: bg, cs_CZ: cs, fi_FI: fi

[o:nextcloud:p:nextcloud:r:{{APPID}}]
file_filter = translationfiles/<lang>/{{APPID}}.po
source_file = translationfiles/templates/{{APPID}}.pot
source_lang = en
type        = PO
```

![image](https://user-images.githubusercontent.com/19730957/221865993-67da6e36-97d0-49d6-bb61-e9279f81f9d7.png)

# 🏗️ Sysadmin team
- [x] 👀 Ensure access:
    - [ ] Nextcloud organisation repository: Add `nextcloud-bot` with admin permissions
    - [x] Other repositories:
        - [x] Ensure the invite was accepted
        - [x] Ensure the app certificate is linked to the same repository/author https://github.com/nextcloud/app-certificate-requests
- [x] ⚙️ Ensure repository setup:
    - [x] `.tx/config`
    - [x] `l10n/.gitkeep`
    - [x] `.l10ignore`
- [x] ➕ Add `"Owner Repository",` into https://github.com/nextcloud/docker-ci/edit/master/translations/config.json
    - [x] Pull request: https://github.com/nextcloud/docker-ci/pull/519
- [x] 🔑 SSH into translation machine: `ssh root@transifex-sync.nextcloud.com`
- [x] ↩️ Change dir: `cd /srv/docker-ci`
- [x] ⬇️ Pull: `git pull origin master`
- [ ] 🧑‍💻 Run the first sync manually:

```sh
docker run -v /srv/cronie-data/transifexrc:/root/.transifexrc \
    -v /srv/cronie-data/gpg:/gpg \
    -v /srv/cronie-data/ssh/id_rsa:/root/.ssh/id_rsa \
    --rm -i ghcr.io/nextcloud/continuous-integration-translations-app \
    AUTHOR APPID
```

# 🔣 Translation team
- [ ] Transifex: New resource should appear
- [ ] Transifex: Do translations and check sync to repo
- [ ] Add resource to [wiki](https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312/)

**Comment by nickvergessen** [comment]
Will do on friday

**Comment by nickvergessen** [comment]
Sync fails at the moment, can you add the `.tx/config` and other files also to the stable24 and stable25 branch?

**Comment by nickvergessen** [comment]
Otherwise add a `.tx/backport` file with content `master` to not backport translations

**Comment by R0Wi** [comment]
> Sync fails at the moment, can you add the `.tx/config` and other files also to the stable24 and stable25 branch?

Done :heavy_check_mark:

**Comment by nickvergessen** [comment]
Translation works now:
https://github.com/R0Wi-DEV/workflow_ocr/commit/e0f643075899b48cc6c1fc2203c4b9f1bae46e5f

**Comment by R0Wi** [comment]
Awesome, thank you soo much! :rocket:
