### ISSUE TITLE
Tables Android app

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/docker-ci#546]
# 👤 App repository

## :warning: Attention! This is an **ANDROID** app.

**To be done by you**

- [x] Link to your repository: https://github.com/stefan-niedermann/nextcloud-tables/
- [x] If the app is not in the Nextcloud organisation
    - [x] Invite `nextcloud-bot` with write permissions
    - [x] Make sure all translated branches do **not** have branch protection enabled, see https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#setup-of-the-transifex-sync for more details
- [ ] Create file `l10n/.gitkeep` with empty content
  **Sure? The Deck Android app doesn't have this either, I think this is only for Server apps?**
- [ ] Add `.l10nignore` to exclude compiled JS files and thirdparty code, e.g. ignoring compiled javascript assets and composer PHP dependencies in the vendor/ directory:
  **Sure? The Deck Android app doesn't have this either, I think this is only for Server apps?**
```
js/
vendor/
```
- [x] Create file `.tx/config` with the following content, replace `{{APPID}}` with your app id 3 times:
```ini
[main]
host     = https://www.transifex.com
lang_map = hu_HU: hu, nb_NO: nb, sk_SK: sk, th_TH: th, ja_JP: ja, bg_BG: bg, cs_CZ: cs, fi_FI: fi

[o:nextcloud:p:nextcloud:r:{{APPID}}]
file_filter = translationfiles/<lang>/{{APPID}}.po
source_file = translationfiles/templates/{{APPID}}.pot
source_lang = en
type        = PO
```

# 🏗️ Sysadmin team
- [x] 👀 Ensure access:
    - [ ] Nextcloud organisation repository: Add `nextcloud-bot` with admin permissions
    - [x] Other repositories:
        - [ ] Ensure the invite was accepted
        - [ ] Ensure the app certificate is linked to the same repository/author https://github.com/nextcloud/app-certificate-requests
- [x] ⚙️ Ensure repository setup:
    - [x] `.tx/config`
    - [ ] `l10n/.gitkeep`
    - [ ] `.l10ignore`
- [x] ➕ Add `"Owner Repository",` into https://github.com/nextcloud/docker-ci/edit/master/translations/config.json
    - [x] Pull request: https://github.com/nextcloud/docker-ci/pull/548/
- [x] 🔑 SSH into translation machine: `ssh root@transifex-sync.nextcloud.com`
- [x] ↩️ Change dir: `cd /srv/docker-ci`
- [x] ⬇️ Pull: `git pull origin master`
- [x] 🧑‍💻 Run the first sync manually:

```sh
docker run -v /srv/cronie-data/transifexrc:/root/.transifexrc \
    -v /srv/cronie-data/gpg:/gpg \
    -v /srv/cronie-data/ssh/id_rsa:/root/.ssh/id_rsa \
    --rm -i ghcr.io/nextcloud/continuous-integration-translations-plain \
    stefan-niedermann nextcloud-tables
```

# 🔣 Translation team
- [ ] Transifex: New resource should appear
- [ ] Transifex: Do translations and check sync to repo
- [ ] Add resource to [wiki](https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312/)

**Comment by nickvergessen** [comment]
Had to add "main" support to the Docker image:
https://github.com/nextcloud/docker-ci/pull/548/commits/1d586f7e1da7cfd3374cf8aa79e68594895d3b0e

But it seems to have worked:
https://github.com/stefan-niedermann/nextcloud-tables/commit/f1e4ff12a323ea09245ec0517be41d01fb2fc58a

**Comment by nickvergessen** [comment]
Hmm but the resource is named `strings.xml` somehow in transifex.

**Comment by stefan-niedermann** [comment]
Woohoo :sparkles: Thank you very much!

> Hmm but the resource is named strings.xml somehow in transifex.

Did I miss some configuration somewhere? Or does this need a fix in the Docker image?

**Comment by nickvergessen** [comment]
Maybe it's the fact that resources now have a slug/id and a different name.
Name is files with the file name by default, so strings.xml for this and `appid.pot` for all others.

Renamed it and still seems to sync. so let's see how it goes.

**Comment by nickvergessen** [comment]
https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312/80?u=nickvergessen
