### ISSUE TITLE
🔣 Translations for files_reminders

### ISSUE THREAD

**Issue by Pytal** [nextcloud/docker-ci#569]
# 👤 App repository

**To be done by you**

- [x] Link to your repository: https://github.com/nextcloud/server/tree/master/apps/files_reminders
- [x] Create file `l10n/.gitkeep` with empty content https://github.com/nextcloud/server/pull/39820
- [x] Create file `.tx/config` with the following content, replace `{{APPID}}` with your app id 3 times: https://github.com/nextcloud/server/pull/39820

# 🏗️ Sysadmin team
- [x] 👀 Ensure access:
    - [x] Nextcloud organisation repository: Add `nextcloud-bot` with admin permissions
    - [ ] Other repositories:
        - [ ] Ensure the invite was accepted
        - [ ] Ensure the app certificate is linked to the same repository/author https://github.com/nextcloud/app-certificate-requests
- [x] ⚙️ Ensure repository setup:
    - [x] `.tx/config`
    - [ ] `l10n/.gitkeep`
    - [ ] `.l10ignore`
- [ ] ➕ Add `"Owner Repository",` into https://github.com/nextcloud/docker-ci/edit/master/translations/config.json
    - [ ] Pull request:
- [ ] 🔑 SSH into translation machine: `ssh root@transifex-sync.nextcloud.com`
- [ ] ↩️ Change dir: `cd /srv/docker-ci`
- [ ] ⬇️ Pull: `git pull origin master`
- [ ] 🧑‍💻 Run the first sync manually:

```sh
docker run -v /srv/cronie-data/transifexrc:/root/.transifexrc \
    -v /srv/cronie-data/gpg:/gpg \
    -v /srv/cronie-data/ssh/id_rsa:/root/.ssh/id_rsa \
    --rm -i ghcr.io/nextcloud/continuous-integration-translations-app \
    AUTHOR APPID
```

# 🔣 Translation team
- [x] Transifex: New resource should appear
- [x] Transifex: Do translations and check sync to repo
- [x] Add resource to [wiki](https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312/)

**Comment by nickvergessen** [comment]
Sync worked after merging the server PR:
https://app.transifex.com/nextcloud/nextcloud/files_reminders/

**Comment by nickvergessen** [comment]
So only proceeding with the after steps.
