### ISSUE TITLE
Add thesearchpage application to nextcloud transifex

### ISSUE THREAD

**Issue by callmemagnus** [nextcloud/docker-ci#607]
# 👤 App repository

**To be done by you**

- [x] Link to your repository: https://github.com/callmemagnus/nextcloud-searchpage
- [x] If the app is not in the Nextcloud organisation
    - [x] Invite `nextcloud-bot` with write permissions
    - [x] Make sure all translated branches do **not** have branch protection enabled, see https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#setup-of-the-transifex-sync for more details
- [x] Create file `l10n/.gitkeep` with empty content
- [x] Add `.l10nignore` to exclude compiled JS files and thirdparty code, e.g. ignoring compiled javascript assets and composer PHP dependencies in the vendor/ directory:
```
js/
vendor/
```
- [x] Create file `.tx/config` with the following content, replace `{{APPID}}` with your app id 3 times:
```ini
[main]
host     = https://www.transifex.com
lang_map = hu_HU: hu, nb_NO: nb, sk_SK: sk, th_TH: th, ja_JP: ja, bg_BG: bg, cs_CZ: cs, fi_FI: fi

[o:nextcloud:p:nextcloud:r:{{APPID}}]
file_filter = translationfiles/<lang>/{{APPID}}.po
source_file = translationfiles/templates/{{APPID}}.pot
source_lang = en
type        = PO
```

# 🏗️ Sysadmin team
- [x] 👀 Ensure access:
    - [ ] Nextcloud organisation repository: Add `nextcloud-bot` with admin permissions
    - [x] Other repositories:
        - [x] Ensure the invite was accepted
        - [x] Ensure the app certificate is linked to the same repository/author https://github.com/nextcloud/app-certificate-requests
- [x] ⚙️ Ensure repository setup:
    - [x] `.tx/config`
    - [x] `l10n/.gitkeep`
    - [x] `.l10ignore`
- [x] ➕ Add `"Owner Repository",` into https://github.com/nextcloud/docker-ci/edit/master/translations/config.json
    - [x] Pull request:
- [x] 🔑 SSH into translation machine: `ssh root@transifex-sync.nextcloud.com`
- [x] ↩️ Change dir: `cd /srv/docker-ci`
- [x] ⬇️ Pull: `git pull origin master`
- [x] 🧑‍💻 Run the first sync manually:

```sh
docker run -v /srv/cronie-data/transifexrc:/root/.transifexrc \
    -v /srv/cronie-data/gpg:/gpg \
    -v /srv/cronie-data/ssh/id_rsa:/root/.ssh/id_rsa \
    --rm -i ghcr.io/nextcloud/continuous-integration-translations-app \
    AUTHOR APPID
```

# 🔣 Translation team
- [x] Transifex: New resource should appear
- [x] Transifex: Do translations and check sync to repo
- [x] Add resource to [wiki](https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312/)

**Comment by nickvergessen** [comment]
Will have a look, mostlikely on friday

**Comment by callmemagnus** [comment]
I merged your PR. Is there anything else I need to do ?

**Comment by nickvergessen** [comment]
So I synced the translations, but just for your information, the `svelte` seem to not be handled properly:
This string is not in the list of translated strings:
https://github.com/callmemagnus/nextcloud-searchpage/blob/main/src/components/Header/SearchBox.svelte#L91

**Comment by callmemagnus** [comment]
> So I synced the translations, but just for your information, the svelte seem to not be handled properly:

Indeed, none of them are correctly handled :-(

Is there a way for me to investigate it further ?

**Comment by nickvergessen** [comment]
Maybe https://github.com/nextcloud/docker-ci/issues/475#issuecomment-1345336780 can give you a trace?

**Comment by callmemagnus** [comment]
Ok. So I need to generate a fake `.js` file so that the translation CI can parse it ?

Is this a correct understanding ?

**Comment by nickvergessen** [comment]
Yes, that would work

**Comment by callmemagnus** [comment]
What is the function name that is search in the files ?

I see `translate` is exported from  @nextcloud/l10n but the comment you mentioned talks about `t`.

**Comment by callmemagnus** [comment]
I pushed the script and the fake label file to `develop`.

Are you able to trigger the job to test it on that branch ? (Or can I do it ?)

**Comment by callmemagnus** [comment]
Ok I used the translationtool.phar and it expects `t(`

**Comment by callmemagnus** [comment]
Pushed a new version to `develop` that "works" with a local translationtool.phar

**Comment by nickvergessen** [comment]
https://github.com/callmemagnus/nextcloud-searchpage/commit/3039ad5b9720f16eb54905c3b68295622960b869

Works now. Also the new strings are found:
![grafik](https://github.com/nextcloud/docker-ci/assets/213943/a34c42e8-e90a-4442-bd91-c17248220843)

**Comment by callmemagnus** [comment]
Thank you!

**Comment by callmemagnus** [comment]
@nickvergessen sorry to bother you again but I have the feeling that only develop is retrieved.

E.g. my app description is different on develop than on main but I only see the one from develop on transifex.

**Comment by nickvergessen** [comment]
all strings are combined, it starts with the master/main branch, so yeah the alter branches would win on the description it seems.

**Comment by nickvergessen** [comment]
Ah, but here we say `use-first`:
https://github.com/nextcloud/docker-ci/blob/master/translations-app/handleAppTranslations.sh#L76

So that should be it.

**Comment by nickvergessen** [comment]
```
      --use-first             use first available translation for each
                              message, don't merge several translations
```

I guess we should turn it around, so that master/main wins

**Comment by nickvergessen** [comment]
So we fixed that in the code, but can't roll out a new version of the container until next week

**Comment by callmemagnus** [comment]
> all strings are combined, it starts with the master/main branch, so yeah the alter branches would win on the description it seems.
> 
> Hmm actually it should be the otherway around: https://github.com/nextcloud/docker-ci/blob/master/translations-app/handleAppTranslations.sh#L37

Are the labels from the info.xml somewhat handled differently than labels from the code ?

I would have guessed that the scrapper just returned all values from main and develop in my case and made them available on the translation site. 

My issues are: 
- info.xml labels (only description from develop is uploaded to transifex)
- label updates in develop do not appear (what is the scan interval ?)

**Comment by nickvergessen** [comment]
> Are the labels from the info.xml somewhat handled differently than labels from the code ?

Hmm after checking the code, the answer should be no:
https://github.com/nextcloud/docker-ci/blob/master/translations/translationtool/src/translationtool.php#L293-L314

It should work the same way, so not sure why the one from your master is not picked up
