### ISSUE TITLE
Translation issue: main is sync not happening anymore

### ISSUE THREAD

**Issue by callmemagnus** [nextcloud/docker-ci#614]
Hi,

A little bit on context:

- my application: https://github.com/callmemagnus/nextcloud-searchpage
- transifex: https://app.transifex.com/nextcloud/nextcloud/thesearchpage/

we (@nickvergessen and me)'ve gone through the setup of my Nextcloud application to move the translation into Transifex (https://github.com/nextcloud/docker-ci/issues/607).

My application was shortly updated by the nextcloud-bot on November 10:

- https://github.com/callmemagnus/nextcloud-searchpage/commit/3039ad5b9720f16eb54905c3b68295622960b869
- https://github.com/callmemagnus/nextcloud-searchpage/commit/259d9392a45346889ff76251abf31b436fa7fc5c

Since then, nothing but I know that there are awaiting validated translations: e.g. Turkmen and Ukrainian.

But those are not sync'd.

I checked my configuration and the [guide](https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html) but cannot see the issue.

My questions:

1. Can someone help me fix the sync ?
2. Is there a way for me to get feedback on issues that the CI might encounter with regards to my repository ?
3. I have translated completely the application in French (my language), how can I get it verified ? 
4. I also see that my `develop` branch does not get scanned for new translations, I added it to the configuration but it is not added automatically, how can I achieve that ?

Thanks in advance.

**Comment by nickvergessen** [comment]
I somehow missed this step:

> ➕ Add "Owner Repository", into https://github.com/nextcloud/docker-ci/edit/master/translations/config.json
>   - Pull request:

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/docker-ci/pull/620

**Comment by nickvergessen** [comment]
https://github.com/callmemagnus/nextcloud-searchpage/commit/a3294ab6be5ff7c55ceee156b811ad1008979668
