### ISSUE TITLE
mail_roundcube w/ nextcloud-bot for translation

### ISSUE THREAD

**Issue by HLFH** [nextcloud/docker-ci#622]
# 👤 App repository

**To be done by you**

- [x] Link to your repository: https://github.com/HLFH/mail_roundcube
- [x] If the app is not in the Nextcloud organisation
    - [x] Invite `nextcloud-bot` with write permissions
    - [x] Make sure all translated branches do **not** have branch protection enabled, see https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#setup-of-the-transifex-sync for more details
- [x] Create file `l10n/.gitkeep` with empty content
- [x] Add `.l10nignore` to exclude compiled JS files and thirdparty code, e.g. ignoring compiled javascript assets and composer PHP dependencies in the vendor/ directory:
```
js/
vendor/
```
- [x] Create file `.tx/config` with the following content, replace `{{APPID}}` with your app id 3 times:
```ini
[main]
host     = https://www.transifex.com
lang_map = hu_HU: hu, nb_NO: nb, sk_SK: sk, th_TH: th, ja_JP: ja, bg_BG: bg, cs_CZ: cs, fi_FI: fi

[o:nextcloud:p:nextcloud:r:{{APPID}}]
file_filter = translationfiles/<lang>/{{APPID}}.po
source_file = translationfiles/templates/{{APPID}}.pot
source_lang = en
type        = PO
```

# 🏗️ Sysadmin team
- [ ] 👀 Ensure access:
    - [ ] Nextcloud organisation repository: Add `nextcloud-bot` with admin permissions
    - [x] Other repositories:
        - [ ] Ensure the invite was accepted
        - [ ] Ensure the app certificate is linked to the same repository/author https://github.com/nextcloud/app-certificate-requests
- [ ] ⚙️ Ensure repository setup:
    - [ ] `.tx/config`
    - [ ] `l10n/.gitkeep`
    - [ ] `.l10nignore`
- [ ] ➕ Add `"Owner Repository",` into https://github.com/nextcloud/docker-ci/edit/master/translations/config.json
    - [ ] Pull request:
- [ ] 🔑 SSH into translation machine: `ssh root@transifex-sync.nextcloud.com`
- [ ] ↩️ Change dir: `cd /srv/docker-ci`
- [ ] ⬇️ Pull: `git pull origin master`
- [ ] 🧑‍💻 Run the first sync manually:

```sh
docker run -v /srv/cronie-data/transifexrc:/root/.transifexrc \
    -v /srv/cronie-data/gpg:/gpg \
    -v /srv/cronie-data/ssh/id_rsa:/root/.ssh/id_rsa \
    --rm -i ghcr.io/nextcloud/continuous-integration-translations-app \
    AUTHOR APPID
```

# 🔣 Translation team
- [ ] Transifex: New resource should appear
- [ ] Transifex: Do translations and check sync to repo
- [ ] Add resource to [wiki](https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312/)

**Comment by nickvergessen** [comment]
I asked sysadmin to accept the invite and will do the rest on Friday mostlikely

**Comment by nickvergessen** [comment]
PS, can you put some light onto the situation? The app is already translated in the original repo https://github.com/rotdrop/nextcloud-roundcube

Also the app seems to be still developed there.
As per our rules the owner of the app certificate will receive the translations, to avoid confusion.
