### ISSUE TITLE
Add Share Review to transifex

### ISSUE THREAD

**Issue by Rello** [nextcloud/docker-ci#647]
# 👤 App repository

**To be done by you**

- [x] Link to your repository: https://github.com/rello/sharereview
- [x] If the app is not in the Nextcloud organisation
    - [x] Invite `nextcloud-bot` with write permissions
    - [x] Make sure all translated branches do **not** have branch protection enabled, see https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#setup-of-the-transifex-sync for more details
- [x] Create file `l10n/.gitkeep` with empty content
- [x] Add `.l10nignore` to exclude compiled JS files and thirdparty code, e.g. ignoring compiled javascript assets and composer PHP dependencies in the vendor/ directory:
- [x] Create file `.tx/config` with the following content, replace `{{APPID}}` with your app id 3 times:

# 🏗️ Sysadmin team
- [x] 👀 Ensure access:
    - [x] Nextcloud organisation repository: Add `nextcloud-bot` with admin permissions
    - [x] Other repositories:
        - [x] Ensure the invite was accepted
        - [x] Ensure the app certificate is linked to the same repository/author https://github.com/nextcloud/app-certificate-requests
- [x] ⚙️ Ensure repository setup:
    - [x] `.tx/config`
    - [x] `l10n/.gitkeep`
    - [x] `.l10nignore`
- [x] ➕ Add `"Owner Repository",` into https://github.com/nextcloud/docker-ci/edit/master/translations/config.json
    - [x] Pull request: https://github.com/nextcloud/docker-ci/pull/648
- [x] 🔑 SSH into translation machine: `ssh root@transifex-sync.nextcloud.com`
- [x] ↩️ Change dir: `cd /srv/docker-ci`
- [x] ⬇️ Pull: `git pull origin master`
- [x] 🧑‍💻 Run the first sync manually:

```sh
docker run -v /srv/cronie-data/transifexrc:/root/.transifexrc \
    -v /srv/cronie-data/gpg:/gpg \
    -v /srv/cronie-data/ssh/id_rsa:/root/.ssh/id_rsa \
    --rm -i ghcr.io/nextcloud/continuous-integration-translations-app \
    AUTHOR APPID
```

# 🔣 Translation team
- [x] Transifex: New resource should appear
- [x] Transifex: Do translations and check sync to repo
- [ ] Add resource to [wiki](https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312/)

**Comment by nickvergessen** [comment]
First sync at https://github.com/Rello/sharereview/commit/109bdad76cb91895d962565cc9da2a1acc1817d4

**Comment by Rello** [comment]
Thank you!
