### ISSUE TITLE
what's your license(s)?

### ISSUE THREAD

**Issue by StCyr** [nextcloud/docker-ci#649]
Hello,

I have copied file https://github.com/nextcloud/docker-ci/blob/master/translations/translationtool/translationtool.phar into my app to manage my translations, and I would like to attribute copyright and licenses.

What should I use?

Is the following correct?

```
SPDX-FileCopyrightText = "2018 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"
```

**Comment by StCyr** [comment]
poke @ChristophWurst (since I saw the mail app's licenses and copyright are properly attributed)

**Comment by nickvergessen** [comment]
The source code is right next to it:
https://github.com/nextcloud/docker-ci/blob/master/translations/translationtool/src/translationtool.php#L7

so 2017 otherwise it's good:
```
SPDX-FileCopyrightText = "2017 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"
```
