### ISSUE TITLE
Pick up translation strings from html files

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/docker-ci#87]
Over at https://github.com/nextcloud/bookmarks/issues/456 I noticed that the translations in our ejs templates, which reside in html files aren't picked up by the translation bot.

Could html be parsed for strings to translate as well?

**Comment by blizzz** [comment]
@MorrisJobke

**Comment by marcelklehr** [comment]
bump ;)

**Comment by MorrisJobke** [comment]
Yep :) On my list :)

**Comment by MorrisJobke** [comment]
@marcelklehr Sadly not yet. Quite low on my list :/

**Comment by marcelklehr** [comment]
Can I do anything to help this along? Send a PR?

**Comment by MorrisJobke** [comment]
I will have a look into this later today and if not you can check if you manage to update https://github.com/nextcloud/docker-ci/blob/master/translations/translationtool/src/translationtool.php

**Comment by MorrisJobke** [comment]
Was easier than I thought 🙈 - sorry that you needed to wait that long.
